// src/pages/admin/transactions.vue
<template>
  <div>
    <div class="container">
      <div class="section">
        <h1 class="title">VEP Transactions</h1>
        <h2 class="subtitle">Manage every transaction that VEP tracks, as well as manual balance adjustments</h2>
      </div>
    </div>
    <div class="container">
      <div class="section">
        <div class="columns">
          <div class="column">
            <div class="field">
              <label class="label">Sent By</label>
              <div class="control">
                <input class="input" type="search" placeholder="Nation, Ruler, or Alliance name" />
              </div>
            </div>
            <!-- <div class="dropdown">
                    <div class="dropdown-trigger">
                        <div class="field">
                            <label class="label">Sent By</label>
                            <div class="control">
                                <input class="input" type="search" placeholder="Nation or Ruler name" />
                            </div>
                        </div>
                    </div>
                    <div class="dropdown-menu" role="menu">
                        <div class="dropdown-content">
                            <p class="is-size-6" style="padding: 0 12px">Nations</p>
                            <span class="dropdown-item">lilweirdward of Land of Too Much Fun</span>
                            <span class="dropdown-item">Lord Draculea of Transylvania</span>
                            <hr class="dropdown-divider" />
                            <p class="is-size-6" style="padding: 0 12px">Alliances</p>
                            <span class="dropdown-item">Christian Coalition of Countries</span>
                        </div>
                    </div>
                </div> -->
          </div>
          <div class="column">
            <div class="field">
              <label class="label">Received By</label>
              <div class="control">
                <input class="input" type="search" placeholder="Nation, Ruler, or Alliance name" />
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
              <label class="label">Since</label>
              <div class="control">
                <input class="input" type="date" />
              </div>
            </div>
          </div>
          <div class="column">
            <div class="field">
              <label class="label">Until</label>
              <div class="control">
                <input class="input" type="date" />
              </div>
            </div>
          </div>
        </div>
        <div class="tabs is-boxed">
          <ul>
            <li :class="{ 'is-active': currentTab === TRANSACTION_TYPES.aidBased }">
              <a @click="changeTab(TRANSACTION_TYPES.aidBased)">
                <span>Aid-Based</span>
              </a>
            </li>
            <li :class="{ 'is-active': currentTab === TRANSACTION_TYPES.manual }">
              <a @click="changeTab(TRANSACTION_TYPES.manual)">
                <span>Manual</span>
              </a>
            </li>
          </ul>
        </div>
        <div v-if="currentTab === TRANSACTION_TYPES.aidBased" class="table-container">
          <table class="table">
            <thead>
              <tr>
                <th>Actions</th>
                <th>Sending Ruler</th>
                <th>Receiving Ruler</th>
                <th>Status</th>
                <th>Money</th>
                <th>Tech</th>
                <th>Sold</th>
                <th>Reason</th>
                <th>Aid ID</th>
                <th>Start</th>
                <th>Ends</th>
                <th>Lu</th>
                <th>Cc</th>
                <th>Rate</th>
                <th>CT</th>
                <th>CC</th>
                <th>TC</th>
                <th>TT</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(transaction, i) in aidBasedTransactions" :key="i">
                <td>
                  <div class="buttons are-small">
                    <button class="button is-info" @click="editTransaction(transaction)">Edit</button>
                  </div>
                </td>
                <td>{{ transaction.sentBy.rulerName || "" }}</td>
                <td>{{ transaction.receivedBy.rulerName || "" }}</td>
                <td>{{ toAidStatusDescription(transaction.status) }}</td>
                <td>{{ transaction.money }}</td>
                <td>{{ transaction.technology }}</td>
                <td>{{ transaction.soldiers }}</td>
                <td>{{ transaction.reason }}</td>
                <td>{{ transaction.aidId || "" }}</td>
                <td>{{ transaction.startsOn }}</td>
                <td>FIX THIS</td>
                <td>{{ (transaction.code && transaction.code.sendingRole + transaction.code.receivingRole) || "" }}</td>
                <td>{{ transaction.classification }}</td>
                <td>{{ transaction.rate }}</td>
                <td>{{ transaction.cashMovedTechCredit }}</td>
                <td>{{ transaction.cashMovedCashCredit }}</td>
                <td>{{ transaction.techMovedCashCredit }}</td>
                <td>{{ transaction.techMovedTechCredit }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div v-if="currentTab === TRANSACTION_TYPES.manual" class="table-container">
          <button class="button is-success" @click="createTransaction()">Create</button>
          <table class="table">
            <thead>
              <tr>
                <th>Actions</th>
                <th>Ruler Name</th>
                <th>Nation Name</th>
                <th>Adjustment Type</th>
                <th>Reason</th>
                <th>Lu</th>
                <th>Cc</th>
                <th>Rate</th>
                <th>CT</th>
                <th>CC</th>
                <th>TC</th>
                <th>TT</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(transaction, i) in manualTransactions" :key="i">
                <td>
                  <div class="buttons are-small">
                    <button class="button is-info">Edit</button>
                    <button class="button is-danger">Delete</button>
                  </div>
                </td>
                <td>{{ transaction.nation.rulerName }}</td>
                <td>{{ transaction.nation.nationName }}</td>
                <td>FIX THIS</td> <!-- {{ adjustmentTypeNames[transaction.adjustmentType] }} -->
                <td>{{ transaction.reason }}</td>
                <td>{{ transaction.accountCode }}</td>
                <td>{{ transaction.classification }}</td>
                <td>{{ transaction.rate }}</td>
                <td>{{ transaction.cashMovedTechCredit }}</td>
                <td>{{ transaction.cashMovedCashCredit }}</td>
                <td>{{ transaction.techMovedCashCredit }}</td>
                <td>{{ transaction.techMovedTechCredit }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="columns">
          <div class="column is-four-fifths">
            <nav class="pagination is-centered" role="navigation" aria-label="pagination">
              <a class="pagination-previous" @click="changePage(currentPage - 1)">Previous</a>
              <a class="pagination-next" @click="changePage(currentPage + 1)">Next</a>
              <ul class="pagination-list">
                <li>
                  <a class="pagination-link" :class="{ 'is-current': currentPage === 1 }" @click="changePage(1)">
                    1
                  </a>
                </li>
                <li v-if="currentPage <= 3 && totalPages >= 2">
                  <a class="pagination-link" :class="{ 'is-current': currentPage === 2 }" @click="changePage(2)">
                    2
                  </a>
                </li>
                <li v-if="currentPage <= 3 && totalPages >= 3">
                  <a class="pagination-link" :class="{ 'is-current': currentPage === 3 }" @click="changePage(3)">
                    3
                  </a>
                </li>
                <li v-if="currentPage <= 3 && totalPages >= 4">
                  <a class="pagination-link" @click="changePage(4)">4</a>
                </li>
                <li v-if="currentPage <= 3 && totalPages >= 5">
                  <a class="pagination-link" @click="changePage(5)">5</a>
                </li>
                <li v-if="currentPage <= 3 && totalPages >= 7">
                  <span class="pagination-link">&hellip;</span>
                </li>
                <li v-if="currentPage > 3 && totalPages > 6 && totalPages - currentPage > 2">
                  <span class="pagination-link">&hellip;</span>
                </li>
                <li v-if="currentPage > 3 && totalPages > 6 && totalPages - currentPage > 2">
                  <a class="pagination-link" @click="changePage(currentPage - 1)">
                    {{ currentPage - 1 }}
                  </a>
                </li>
                <li v-if="currentPage > 3 && totalPages > 6 && totalPages - currentPage > 2">
                  <a class="pagination-link is-current">
                    {{ currentPage }}
                  </a>
                </li>
                <li v-if="currentPage > 3 && totalPages > 6 && totalPages - currentPage > 2">
                  <a class="pagination-link" @click="changePage(currentPage + 1)">
                    {{ currentPage + 1 }}
                  </a>
                </li>
                <li v-if="currentPage > 3 && totalPages > 6 && totalPages - currentPage > 2">
                  <span class="pagination-link">&hellip;</span>
                </li>
                <li v-if="totalPages > 6 && totalPages - currentPage <= 2">
                  <span class="pagination-link">&hellip;</span>
                </li>
                <li v-if="totalPages > 6 && totalPages - currentPage <= 2">
                  <a class="pagination-link" @click="changePage(totalPages - 4)">
                    {{ totalPages - 4 }}
                  </a>
                </li>
                <li v-if="totalPages > 6 && totalPages - currentPage <= 2">
                  <a class="pagination-link" @click="changePage(1)">
                    {{ totalPages - 3 }}
                  </a>
                </li>
                <li v-if="totalPages > 6 && totalPages - currentPage <= 2">
                  <a
                    class="pagination-link" 
                    :class="{ 'is-current': currentPage === totalPages } - 2"
                    @click="changePage(totalPages - 2)"
                  >
                    {{ totalPages - 2 }}
                  </a>
                </li>
                <li v-if="totalPages > 6 && totalPages - currentPage <= 2">
                  <a
                    class="pagination-link"
                    :class="{ 'is-current': currentPage === totalPages } - 1"
                    @click="changePage(totalPages - 1)"
                  >
                    {{ totalPages - 1 }}
                  </a>
                </li>
                <li v-if="totalPages >= 6">
                  <a
                    class="pagination-link"
                    :class="{ 'is-current': currentPage === totalPages }"
                    @click="changePage(totalPages)"
                  >
                    {{ totalPages }}
                  </a>
                </li>
              </ul>
            </nav>
          </div>
          <div class="column">
            <div class="select">
              <select v-model="limit">
                <option v-for="option in limitOptions" :key="option">
                  {{ option }}
                </option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
    <AdminAidBasedTransactionDialog :show="transactionDialogIsVisible" :transaction="transactionBeingEdited" />
    <AdminManualTransactionDialog :show="true" :transaction="{}" :accounts="accounts" />
  </div>
</template>

<script>
import { mapState, mapGetters, mapActions } from "vuex";
import { TRANSACTION_TYPES } from "~/infrastructure/constants";

export default {
  name: "TransactionsPage",
  data: () => ({
    TRANSACTION_TYPES,
    currentTab: TRANSACTION_TYPES.aidBased,
    currentPage: 1,
    limit: 25,
    limitOptions: [ 10, 25, 100, 500 ],
    transactionDialogIsVisible: false,
    transactionBeingEdited: undefined
  }),
  computed: {
    ...mapState({
      currentTransactionsPage: state => state.admin.transactions.currentTransactionsPage,
      accounts: state => state.admin.accounts.accounts
    }),
    ...mapGetters({
      aidBasedTransactions: "admin/transactions/aidBasedTransactions",
      manualTransactions: "admin/transactions/manualTransactions"
    }),
    totalPages() {
      return Math.ceil(this.currentTransactionsPage.totalCount / 100);
    },
    tabIsAidBased() {
      return this.currentTab === TRANSACTION_TYPES.aidBased;
    },
    tabIsManual() {
      return this.currentTab === TRANSACTION_TYPES.manual;
    }
  },
  async created() {
    await this.changePage(1);
    this.$log.info(this.currentTransactionsPage);

    await this.loadAllAccounts();
    this.$log.info(this.accounts);
  },
  methods: {
    ...mapActions({
      reloadCurrentTransactionsPage: "admin/transactions/reloadCurrentTransactionsPage",
      loadAllAccounts: "admin/accounts/loadAllAccounts"
    }),
    async changePage(newPageNumber) {
      this.currentPage = newPageNumber;
      await this.reloadCurrentTransactionsPage({
        type: this.currentTab,
        filter: {},
        limit: this.limit,
        offset: this.limit * (this.currentPage - 1)
      });
    },
    async changeTab(tabName) {
      if (this.currentTab === tabName) {
        this.$log.warn("The same tab that is already active was clicked, so nothing will happen.");
        return;
      }

      this.currentTab = tabName;
      await this.changePage(1);
    },
    toAidStatusDescription(statusId) {
      switch (statusId) {
        case 1: return "Pending";
        case 2: return "Approved";
        case 3: return "Cancelled";
        case 4: return "Expired";
        default: return "Unknown";
      }
    },
    createTransaction() {
      this.transactionBeingEdited = {};
      this.transactionDialogIsVisible = true;
    },
    editTransaction(txn) {
      this.transactionBeingEdited = txn;
      this.transactionDialogIsVisible = true;
    }
  }
}
</script>

// src/client/src/app/admin/transactions/transactions.component.ts
import { AfterViewInit, Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import bulmaCalendar from 'bulma-calendar';

@Component({
  selector: 'app-transactions',
  templateUrl: './transactions.component.html',
  styleUrls: ['./transactions.component.scss']
})
export class TransactionsComponent implements AfterViewInit {

  @ViewChild("aidSinceCalendar") aidSinceCalendar: ElementRef<HTMLInputElement> | undefined;
  @ViewChild("aidUntilCalendar") aidUntilCalendar: ElementRef<HTMLInputElement> | undefined;

  constructor() { }

  ngAfterViewInit(): void {
    const aidSince = bulmaCalendar.attach(this.aidSinceCalendar?.nativeElement)[0];
    aidSince.on("select", e => console.log(e));

    const aidUntil = bulmaCalendar.attach(this.aidUntilCalendar?.nativeElement)[0];
    aidUntil.on("select", e => console.log(e));
  }

}

<div class="container">
    <div class="section">
        <h1 class="title">VEP Transactions</h1>
        <h2 class="subtitle">Manage every transaction that VEP tracks, as well as manual balance adjustments</h2>
    </div>
</div>
<div class="container">
    <div class="section">
        <div class="columns">
            <div class="column">
                <div class="field">
                    <label class="label">Sent By</label>
                    <div class="control">
                        <input #sentBy class="input" type="search" placeholder="Nation, Ruler, or Alliance name" />
                    </div>
                </div>
                <!-- <div class="dropdown">
                    <div class="dropdown-trigger">
                        <div class="field">
                            <label class="label">Sent By</label>
                            <div class="control">
                                <input class="input" type="search" placeholder="Nation or Ruler name" />
                            </div>
                        </div>
                    </div>
                    <div class="dropdown-menu" role="menu">
                        <div class="dropdown-content">
                            <p class="is-size-6" style="padding: 0 12px">Nations</p>
                            <span class="dropdown-item">lilweirdward of Land of Too Much Fun</span>
                            <span class="dropdown-item">Lord Draculea of Transylvania</span>
                            <hr class="dropdown-divider" />
                            <p class="is-size-6" style="padding: 0 12px">Alliances</p>
                            <span class="dropdown-item">Christian Coalition of Countries</span>
                        </div>
                    </div>
                </div> -->
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">Received By</label>
                    <div class="control">
                        <input #receivedBy class="input" type="search" placeholder="Nation, Ruler, or Alliance name" />
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">Since</label>
                    <div class="control">
                        <input #aidSinceCalendar class="input" type="date" />
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label class="label">Until</label>
                    <div class="control">
                        <input #aidUntilCalendar class="input" type="date" />
                    </div>
                </div>
            </div>
        </div>
        <div class="tabs is-boxed">
            <ul>
                <li [class.is-active]="currentTab === transactionType.AidBased">
                    <a>
                        <span (click)="switchTab(transactionType.AidBased)">Aid-Based</span>
                    </a>
                </li>
                <li [class.is-active]="currentTab === transactionType.Manual">
                    <a>
                        <span (click)="switchTab(transactionType.Manual)">Manual</span>
                    </a>
                </li>
            </ul>
        </div>
        <div *ngIf="currentTab === transactionType.AidBased" class="table-container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>Sending Ruler</th>
                        <th>Receiving Ruler</th>
                        <th>Status</th>
                        <th>Money</th>
                        <th>Tech</th>
                        <th>Sold</th>
                        <th>Reason</th>
                        <th>Aid ID</th>
                        <th>Start</th>
                        <th>Ends</th>
                        <th>Lu</th>
                        <th>Cc</th>
                        <th>Rate</th>
                        <th>CT</th>
                        <th>CC</th>
                        <th>TC</th>
                        <th>TT</th>
                    </tr>
                </thead>
                <tbody>
                    <tr *ngFor="let transaction of aidBasedTransactions;">
                        <td>
                            <div class="buttons are-small">
                                <button class="button is-info">Edit</button>
                            </div>
                        </td>
                        <td>{{ transaction.sentBy?.rulerName || "" }}</td>
                        <td>{{ transaction.receivedBy?.rulerName || "" }}</td>
                        <td>{{ aidStatusNames[transaction.status] }}</td>
                        <td>{{ transaction.money }}</td>
                        <td>{{ transaction.technology }}</td>
                        <td>{{ transaction.soldiers }}</td>
                        <td>{{ transaction.reason }}</td>
                        <td>{{ transaction.aidId || "" }}</td>
                        <td>{{ transaction.startsOn }}</td>
                        <td>FIX THIS</td>
                        <td>{{ (transaction.code && transaction.code.sendingRole + transaction.code.receivingRole) || "" }}</td>
                        <td>{{ transaction.classification }}</td>
                        <td>{{ transaction.rate }}</td>
                        <td>{{ transaction.cashMovedTechCredit }}</td>
                        <td>{{ transaction.cashMovedCashCredit }}</td>
                        <td>{{ transaction.techMovedCashCredit }}</td>
                        <td>{{ transaction.techMovedTechCredit }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div *ngIf="currentTab === transactionType.Manual" class="table-container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>Ruler Name</th>
                        <th>Nation Name</th>
                        <th>Adjustment Type</th>
                        <th>Reason</th>
                        <th>Lu</th>
                        <th>Cc</th>
                        <th>Rate</th>
                        <th>CT</th>
                        <th>CC</th>
                        <th>TC</th>
                        <th>TT</th>
                    </tr>
                </thead>
                <tbody>
                    <tr *ngFor="let transaction of manualTransactions;">
                        <td>
                            <div class="buttons are-small">
                                <button class="button is-info">Edit</button>
                                <button class="button is-danger">Delete</button>
                            </div>
                        </td>
                        <td>{{ transaction.sentBy?.rulerName || transaction.receivedBy?.rulerName || "" }}</td>
                        <td>{{ transaction.sentBy?.nationName || transaction.receivedBy?.nationName || "" }}</td>
                        <td>{{ transaction.sentBy !== undefined ? "Credit" : transaction.receivedBy !== undefined ? "Debt" : "BROKEN" }}</td>
                        <td>{{ transaction.reason }}</td>
                        <td>{{ (transaction.code && transaction.code.sendingRole + transaction.code.receivingRole) || "" }}</td>
                        <td>{{ transaction.classification }}</td>
                        <td>{{ transaction.rate }}</td>
                        <td>{{ transaction.cashMovedTechCredit }}</td>
                        <td>{{ transaction.cashMovedCashCredit }}</td>
                        <td>{{ transaction.techMovedCashCredit }}</td>
                        <td>{{ transaction.techMovedTechCredit }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="columns">
            <div class="column is-four-fifths">
                <nav class="pagination is-centered" role="navigation" aria-label="pagination">
                    <a class="pagination-previous">Previous</a>
                    <a class="pagination-next">Next</a>
                    <ul class="pagination-list">
                        <li>
                            <a class="pagination-link" [class.is-current]="currentPage === 1" (click)="changePage(1)">
                                1
                            </a>
                        </li>
                        <ng-container *ngIf="currentPage <= 3 || totalPages <= 6">
                            <li *ngIf="totalPages >= 2">
                                <a class="pagination-link" [class.is-current]="currentPage === 2" (click)="changePage(2)">
                                    2
                                </a>
                            </li>
                            <li *ngIf="totalPages >= 3">
                                <a class="pagination-link" [class.is-current]="currentPage === 3" (click)="changePage(3)">
                                    3
                                </a>
                            </li>
                            <li *ngIf="totalPages >= 4">
                                <a class="pagination-link" (click)="changePage(4)">4</a>
                            </li>
                            <li *ngIf="totalPages >= 5">
                                <a class="pagination-link" (click)="changePage(5)">5</a>
                            </li>
                            <li *ngIf="totalPages >= 7">
                                <span class="pagination-link">&hellip;</span>
                            </li>
                        </ng-container>
                        <ng-container *ngIf="currentPage > 3 && totalPages > 6 && totalPages - currentPage > 2">
                            <li>
                                <span class="pagination-link">&hellip;</span>
                            </li>
                            <li>
                                <a class="pagination-link" (click)="changePage(currentPage - 1)">
                                    {{ currentPage - 1 }}
                                </a>
                            </li>
                            <li>
                                <a class="pagination-link is-current">
                                    {{ currentPage }}
                                </a>
                            </li>
                            <li>
                                <a class="pagination-link" (click)="changePage(currentPage + 1)">
                                    {{ currentPage + 1 }}
                                </a>
                            </li>
                            <li>
                                <span class="pagination-link">&hellip;</span>
                            </li>
                        </ng-container>
                        <ng-container *ngIf="totalPages > 6 && totalPages - currentPage <= 2">
                            <li>
                                <span class="pagination-link">&hellip;</span>
                            </li>
                            <li>
                                <a class="pagination-link" (click)="changePage(totalPages - 4)">
                                    {{ totalPages - 4 }}
                                </a>
                            </li>
                            <li>
                                <a class="pagination-link" (click)="changePage(1)">
                                    {{ totalPages - 3 }}
                                </a>
                            </li>
                            <li>
                                <a class="pagination-link" [class.is-current]="currentPage === totalPages - 2" (click)="changePage(totalPages - 2)">
                                    {{ totalPages - 2 }}
                                </a>
                            </li>
                            <li>
                                <a class="pagination-link" [class.is-current]="currentPage === totalPages - 1" (click)="changePage(totalPages - 1)">
                                    {{ totalPages - 1 }}
                                </a>
                            </li>
                        </ng-container>
                        <li *ngIf="totalPages >= 6">
                            <a class="pagination-link" [class.is-current]="currentPage === totalPages" (click)="changePage(totalPages)">
                                {{ totalPages }}
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="column">
                <div class="dropdown is-up" [class.is-active]="limitDropdownVisible">
                    <div class="dropdown-trigger">
                        <button class="button" (click)="limitDropdownVisible = !limitDropdownVisible">
                            Results Per Page
                        </button>
                    </div>
                    <div class="dropdown-menu" role="menu">
                        <div class="dropdown-content">
                            <a *ngFor="let option of limitOptions; index as i;" class="dropdown-item"
                                [class.is-active]="selectedLimit === i" (click)="limitDropdownSelectChanged(i)">
                                {{ option }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
