// src/client/pages/admin/accounts.vue
<template>
  <div>
    <div class="container">
      <div class="section">
        <h1 class="title">VEP Accounts</h1>
        <h2 class="subtitle">Manage accounts enrolled in VEP, or enroll new accounts</h2>
      </div>
    </div>
    <div class="container">
      <div class="section table-container">
        <button class="button is-success" @click="createAccount()">Create</button>
        <table class="table is-hoverable">
          <thead>
            <tr>
              <th>Actions</th>
              <th>NationID</th>
              <th>Ruler</th>
              <th>Nation</th>
              <th>Discord</th>
              <th>DiscordID</th>
              <th>PSW</th>
              <th>VA</th>
              <th>AA</th>
              <th>Activity</th>
              <th>Strength</th>
              <th>Infra</th>
              <th>Tech</th>
              <th>War</th>
              <th>FM</th>
              <th>FAC</th>
              <th>DRA</th>
              <th>Free</th>
              <th>Full</th>
              <th>sCash</th>
              <th>sTech</th>
              <th>Credit</th>
              <th>Debt</th>
              <th>ctB</th>
              <th>ctS</th>
              <th>ccB</th>
              <th>ccS</th>
              <th>tcB</th>
              <th>tcS</th>
              <th>ttB</th>
              <th>ttS</th>
              <th>Prv</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(account, i) in accounts" :key="i">
              <td>
                <div class="buttons are-small">
                  <button class="button is-info" @click="editAccount(account)">Edit</button>
                  <button
                    class="button is-danger"
                    :class="{ 'is-loading': accountIdBeingDeleted === account.id }"
                    @click="deleteAccountById(account.id)"
                  >
                    Delete
                  </button>
                </div>
              </td>
              <td>{{ account.nationId }}</td>
              <td>{{ account.rulerName }}</td>
              <td>{{ account.nationName }}</td>
              <td>{{ account.discord }}</td>
              <td>{{ account.discordUniqueId }}</td>
              <td>{{ account.uniqueCode }}</td>
              <td>{{ account.role }}</td>
              <td>{{ account.allianceName }}</td>
              <td>{{ account.activity }}</td>
              <td>{{ account.strength }}</td>
              <td>{{ account.infra }}</td>
              <td>{{ account.tech }}</td>
              <td>{{ account.warStatus === 1 ? "WM" : "PM" }}</td>
              <td>{{ account.hasForeignMinistry }}</td>
              <td>{{ account.hasFederalAidCommission }}</td>
              <td>{{ account.hasDisasterReliefAgency }}</td>
              <td>{{ account.slotsFull - account.slotsUsed }}</td>
              <td>{{ account.slotsFull }}</td>
              <td>{{ account.totalCashSent - account.totalCashReceived }}</td>
              <td>{{ account.totalTechSent - account.totalTechReceived }}</td>
              <td>{{ account.credit }}</td>
              <td>{{ account.debt }}</td>
              <td>{{ account.cashSentTechCredit }}</td>
              <td>{{ account.cashReceivedTechCredit }}</td>
              <td>{{ account.cashSentCashCredit }}</td>
              <td>{{ account.cashReceivedCashCredit }}</td>
              <td>{{ account.techSentCashCredit }}</td>
              <td>{{ account.techReceivedCashCredit }}</td>
              <td>{{ account.techSentTechCredit }}</td>
              <td>{{ account.techReceivedTechCredit }}</td>
              <td>{{ account.previousListOrder }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <AdminAccountEditDialog 
      :account="accountBeingEdited" 
      :show="editDialogIsVisible"
      @close="closeAccountEditDialog()" 
    />
  </div>
</template>

<script>
import { mapActions, mapState } from 'vuex';

export default {
  name: 'AccountsPage',
  data: () => ({
    editDialogIsVisible: false,
    accountBeingEdited: undefined,
    accountIdBeingDeleted: 0
  }),
  computed: {
    ...mapState({
      accounts: state => state.admin.accounts.accounts
    })
  },
  created() {
    this.loadAllAccounts();
    this.$log.info(this.accounts);
  },
  methods: {
    ...mapActions({
      loadAllAccounts: "admin/accounts/loadAllAccounts",
      deleteAccount: "admin/accounts/deleteAccount"
    }),
    createAccount() {
      this.accountBeingEdited = {};
      this.editDialogIsVisible = true;
    },
    editAccount(account) {
      this.accountBeingEdited = account;
      this.editDialogIsVisible = true;
    },
    async deleteAccountById(accountId) {
      this.accountIdBeingDeleted = accountId;

      try {
        await this.deleteAccount(accountId);
      } catch (e) {
        this.$log.error(e);
        this.$toast.error("VEP encountered an error while deleting the account. Please try again, or contact @lilweirdward if the error persists.");
      }

      this.accountIdBeingDeleted = 0;
    },
    closeAccountEditDialog() {
      this.accountBeingEdited = undefined;
      this.editDialogIsVisible = false;
    }
  }
}
</script>

// src/client/src/app/admin/accounts/accounts.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subject } from 'rxjs';
import { filter, takeUntil } from 'rxjs/operators';
import { Account } from 'src/app/models/account';
import { VepAdminStore } from 'src/app/store';

@Component({
  selector: 'app-accounts',
  templateUrl: './accounts.component.html',
  styleUrls: ['./accounts.component.scss']
})
export class AccountsComponent implements OnInit, OnDestroy {

  private ngUnsubscribe = new Subject();

  accounts: Account[];
  accountBeingEdited: Account | undefined;
  accountEditorIsVisible: boolean = false;

  constructor(private store$: VepAdminStore) {
    this.accounts = [];
  }

  ngOnInit(): void {
    this.store$.accounts
      .pipe(
        filter(accounts => accounts.length != 0),
        takeUntil(this.ngUnsubscribe)
      )
      .subscribe(accounts => {
        this.accounts = accounts;
      });
    this.store$.dispatch('loadAllAccounts');
  }

  createNewAccount(): void {
    this.accountEditorIsVisible = true;
  }

  editAccount(accountId: number): void {
    const account = this.accounts.find(acc => acc.id === accountId);
    if (account !== undefined) {
      this.accountBeingEdited = Object.assign({}, account);
      this.accountEditorIsVisible = true
    };
  }

  deleteAccount(accountId: number): void {
    this.store$.dispatch('deleteAccount', accountId);
  }

  ngOnDestroy(): void {
    this.ngUnsubscribe.next();
    this.ngUnsubscribe.complete();
  }

}

<div class="container">
    <div class="section">
        <h1 class="title">VEP Accounts</h1>
        <h2 class="subtitle">Manage accounts enrolled in VEP, or enroll new accounts</h2>
    </div>
</div>
<div class="container">
    <div class="section table-container">
        <button class="button is-success" (click)="createNewAccount()">Create</button>
        <table class="table is-hoverable is-bordered">
            <thead>
                <tr>
                    <th>Actions</th>
                    <th>NationID</th>
                    <th>Ruler</th>
                    <th>Nation</th>
                    <th>Discord</th>
                    <th>DiscordID</th>
                    <th>PSW</th>
                    <th>VA</th>
                    <th>AA</th>
                    <th>Activity</th>
                    <th>Strength</th>
                    <th>Infra</th>
                    <th>Tech</th>
                    <th>War</th>
                    <th>FM</th>
                    <th>FAC</th>
                    <th>DRA</th>
                    <th>Free</th>
                    <th>Full</th>
                    <th>sCash</th>
                    <th>sTech</th>
                    <th>Credit</th>
                    <th>Debt</th>
                    <th>Balance</th>
                    <th>ctB</th>
                    <th>ctS</th>
                    <th>ccB</th>
                    <th>ccS</th>
                    <th>tcB</th>
                    <th>tcS</th>
                    <th>ttB</th>
                    <th>ttS</th>
                    <th>Prv</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let account of accounts;">
                    <td>
                        <div class="buttons are-small">
                            <button class="button is-info" (click)="editAccount(account.id)">Edit</button>
                            <button class="button is-danger" (click)="deleteAccount(account.id)">Delete</button>
                        </div>
                    </td>
                    <td>{{ account.nationId }}</td>
                    <td>{{ account.rulerName }}</td>
                    <td>{{ account.nationName }}</td>
                    <td>{{ account.discord }}</td>
                    <td>{{ account.discordUniqueId }}</td>
                    <td>{{ account.uniqueCode }}</td>
                    <td>{{ account.role }}</td>
                    <td>FIX THIS</td>
                    <td>{{ account.activity }}</td>
                    <td>{{ account.strength }}</td>
                    <td>{{ account.infra }}</td>
                    <td>{{ account.tech }}</td>
                    <td>{{ account.warStatus === 1 ? "WM" : "PM" }}</td>
                    <td>{{ account.hasForeignMinistry }}</td>
                    <td>{{ account.hasFederalAidCommission }}</td>
                    <td>{{ account.hasDisasterReliefAgency }}</td>
                    <td>{{ account.slotsFull - account.slotsUsed }}</td>
                    <td>{{ account.slotsFull }}</td>
                    <td>{{ account.totalCashSent - account.totalCashReceived }}</td>
                    <td>{{ account.totalTechSent - account.totalTechReceived }}</td>
                    <td>{{ account.credit }}</td>
                    <td>FIX THIS</td>
                    <td>FIX THIS</td>
                    <td>{{ account.cashSentTechCredit }}</td>
                    <td>{{ account.cashReceivedTechCredit }}</td>
                    <td>{{ account.cashSentCashCredit }}</td>
                    <td>{{ account.cashReceivedCashCredit }}</td>
                    <td>{{ account.techSentCashCredit }}</td>
                    <td>{{ account.techReceivedCashCredit }}</td>
                    <td>{{ account.techSentTechCredit }}</td>
                    <td>{{ account.techReceivedTechCredit }}</td>
                    <td>{{ account.previousListOrder }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<account-editor-dialog [account]="accountBeingEdited" [(isVisible)]="accountEditorIsVisible"></account-editor-dialog>
